<?php


namespace Modules\System\Database\Seeders;


use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $createdTime = Carbon::now()->toDateTimeString();
        DB::table('my_system_menu')->insert([
            [
                'pid' => 0,
                'title' => '系统模块',
                'icon' => 'dripicons-device-desktop',
                'url' => '',
                'target' => '',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 0,
                'title' => '会员模块',
                'icon' => 'dripicons-user-group',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 0,
                'title' => 'CMS模块',
                'icon' => 'dripicons-article',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 0,
                'title' => '商城模块',
                'icon' => 'dripicons-shopping-bag',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 0,
                'title' => '订单模块',
                'icon' => 'dripicons-checklist',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ],
            [
                'pid' => 0,
                'title' => '自媒体模块',
                'icon' => 'dripicons-camcorder',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ],
            [
                'pid' => 0,
                'title' => 'API模块',
                'icon' => 'dripicons-cloud',
                'url' => '',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ],
            [
                'pid' => 1,
                'title' => '网站配置',
                'icon' => '',
                'url' => '/admin/config',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ],
            [
                'pid' => 1,
                'title' => '管理员管理',
                'icon' => '',
                'url' => '/admin/admin',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ],
            [
                'pid' => 1,
                'title' => '角色管理',
                'icon' => '',
                'url' => '/admin/role',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '菜单管理',
                'icon' => '',
                'url' => '/admin/menu',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '插件管理',
                'icon' => '',
                'url' => '/admin/addon',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '辅助属性',
                'icon' => '',
                'url' => '/admin/attr',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '自定义页面',
                'icon' => '',
                'url' => '/admin/diy-page',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '配置管理器',
                'icon' => '',
                'url' => '/admin/system_config',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 1,
                'title' => '模板配置',
                'icon' => '',
                'url' => '/admin/template/config',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 2,
                'title' => '会员管理',
                'icon' => '',
                'url' => '/admin/user',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 2,
                'title' => '会员等级',
                'icon' => '',
                'url' => '/admin/user/rank',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 2,
                'title' => '余额明细',
                'icon' => '',
                'url' => '/admin/user/balance',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 2,
                'title' => '积分明细',
                'icon' => '',
                'url' => '/admin/user/point',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 2,
                'title' => '收货地址',
                'icon' => '',
                'url' => '/admin/user/address',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 3,
                'title' => '文章分类',
                'icon' => '',
                'url' => '/admin/cms/category',
                'target' => '_self',
                'sort' => 1,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 3,
                'title' => '文章列表',
                'icon' => '',
                'url' => '/admin/cms',
                'target' => '_self',
                'sort' => 3,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 3,
                'title' => '文章标签',
                'icon' => '',
                'url' => '/admin/cms/tag',
                'target' => '_self',
                'sort' => 4,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 3,
                'title' => '文章评论',
                'icon' => '',
                'url' => '/admin/cms/comment',
                'target' => '_self',
                'sort' => 5,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 3,
                'title' => '文章分组',
                'icon' => '',
                'url' => '/admin/cms/article_group',
                'target' => '_self',
                'sort' => 2,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 4,
                'title' => '商城配置',
                'icon' => '',
                'url' => '/admin/shop/config',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 4,
                'title' => '支付配置',
                'icon' => '',
                'url' => '/admin/shop/pay/config',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 4,
                'title' => '商品分类',
                'icon' => '',
                'url' => '/admin/shop/category',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 4,
                'title' => '商品列表',
                'icon' => '',
                'url' => '/admin/shop/goods',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 4,
                'title' => '支付流水',
                'icon' => '',
                'url' => '/admin/shop/pay/logs',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 5,
                'title' => '订单管理',
                'icon' => '',
                'url' => '/admin/order',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 6,
                'title' => '自媒体账号',
                'icon' => '',
                'url' => '/admin/mp/mp_account',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 6,
                'title' => '自媒体文章',
                'icon' => '',
                'url' => '/admin/mp/mp_article',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 6,
                'title' => '自媒体模板',
                'icon' => '',
                'url' => '/admin/mp/mp_template',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 6,
                'title' => '自媒体发布',
                'icon' => '',
                'url' => '/admin/mp/mp_push_log',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 7,
                'title' => '接口列表',
                'icon' => '',
                'url' => '/admin/api',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ], [
                'pid' => 7,
                'title' => '数据源管理',
                'icon' => '',
                'url' => '/admin/api/data_source',
                'target' => '_self',
                'sort' => 0,
                'status' => 1,
                'created_at' => $createdTime,
                'updated_at' => $createdTime,
            ]
        ]);
    }
}
